pipeline {
    agent any

    tools {
        maven 'Maven3'
        nodejs 'NodeJS'
    }

    environment {
        DEV_DB_PASSWORD   = credentials('DEV_DB_PASSWORD')
        DEV_DB_URL        = credentials('DEV_DB_URL')
        DEV_DB_USERNAME   = credentials('DEV_DB_USERNAME')
        DEV_JWT_SECRET    = credentials('DEV_JWT_SECRET')
        DEV_MAIL_PASSWORD = credentials('DEV_MAIL_PASSWORD')
        DEV_MAIL_USERNAME = credentials('DEV_MAIL_USERNAME')
        DEV_RAPID_API_KEY = credentials('DEV_RAPID_API_KEY')
        DEV_TWILIO_PHONE  = credentials('DEV_TWILIO_PHONE')
        DEV_TWILIO_SID    = credentials('DEV_TWILIO_SID')
        DEV_TWILIO_TOKEN  = credentials('DEV_TWILIO_TOKEN')
        FIREBASE_CONFIG_PATH = credentials('FIREBASE_CONFIG_PATH')
    }

    stages {

        stage('Clone Backend') {
            steps {
                dir('backend') {
                    git branch: 'main',
                        url: 'https://github.com/satya323k-design/SIVVGTRADINGAPPBACKEND.git'
                }
            }
        }

        stage('Clone Frontend') {
            steps {
                dir('frontend') {
                    git branch: 'main',
                        url: 'https://github.com/satya323k-design/SivvgApp.git'
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    bat 'mvnw.cmd clean install -DskipTests'
                }
            }
        }

        stage('Test Backend') {
            steps {
                dir('backend') {
                    bat 'mvnw.cmd test'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    bat 'npm install'
                    bat 'npm run build'
                }
            }
        }

        stage('Run Backend') {
            steps {
                dir('backend') {
                    bat 'java -jar target\\*.jar'
                }
            }
        }

        stage('Success') {
            steps {
                echo '✅ Fullstack Build + Test + Run Success'
            }
        }
    }
}