pipeline {
    agent any

    environment {
        DEV_JWT_SECRET = credentials('DEV_JWT_SECRET')
    }

    stages {

        stage('Build') {
            steps {
                dir('sivvg-trading-core-services') {
                    bat 'mvnw.cmd clean install -DskipTests'
                }
            }
        }

        stage('Run') {
            steps {
                dir('sivvg-trading-core-services') {
                    bat '''
                    set DEV_JWT_SECRET=%DEV_JWT_SECRET%
                    for %i in (target\\*.jar) do (java -jar %i)
                    '''
                }
            }
        }
    }
}