package com.sivvg.tradingservices.model;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

@Entity
@Table(name = "users")
public class User {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// Unique login id generated by system (like "USR12345")
	@Column(nullable = false, unique = true)
	private String userId;

	@Column(nullable = false)
	private String username; // display name

	@Column(nullable = false, unique = true)
	private String email;

	@Column(nullable = false, unique = true)
	private String phoneNumber;

	@Column(nullable = false)
	private String passwordHash; // bcrypt hashed

	private String gender;
	private String dob;

	private boolean enabled = true;

	// OTP fields for temporary storage (optional; could use separate table)

	private String currentOtp;
	private LocalDateTime otpExpiry;

	// OTP resend tracking
	@Column(nullable = false)
	private int otpResendCount = 0;
	private LocalDateTime otpResendBlockedUntil;

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id"))
	private Set<Role> roles = new HashSet<>();

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "user_status", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "status_id"))
	private Set<Status> status = new HashSet<>();
	private Boolean isFollowingTips;
	private String subscriptionPlan;

	// Generated default constructor, getters/setters

	public User() {
	}

	public User(Long id, String userId, String username, String email, String phoneNumber, String passwordHash,
			String gender, String dob, boolean enabled, String currentOtp, LocalDateTime otpExpiry, int otpResendCount,
			LocalDateTime otpResendBlockedUntil, Set<Role> roles, Set<Status> status, Boolean isFollowingTips,
			String subscriptionPlan) {
		super();
		this.id = id;
		this.userId = userId;
		this.username = username;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.passwordHash = passwordHash;
		this.gender = gender;
		this.dob = dob;
		this.enabled = enabled;
		this.currentOtp = currentOtp;
		this.otpExpiry = otpExpiry;
		this.otpResendCount = otpResendCount;
		this.otpResendBlockedUntil = otpResendBlockedUntil;
		this.roles = roles;
		this.status = status;
		this.isFollowingTips = isFollowingTips;
		this.subscriptionPlan = subscriptionPlan;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPasswordHash() {
		return passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDob() {
		return dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getCurrentOtp() {
		return currentOtp;
	}

	public void setCurrentOtp(String currentOtp) {
		this.currentOtp = currentOtp;
	}

	public LocalDateTime getOtpExpiry() {
		return otpExpiry;
	}

	public void setOtpExpiry(LocalDateTime otpExpiry) {
		this.otpExpiry = otpExpiry;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set<Status> getStatus() {
		return status;
	}

	public void setStatus(Set<Status> status) {
		this.status = status;
	}

	public Boolean getIsFollowingTips() {
		return isFollowingTips;
	}

	public void setIsFollowingTips(Boolean isFollowingTips) {
		this.isFollowingTips = isFollowingTips;
	}

	public String getSubscriptionPlan() {
		return subscriptionPlan;
	}

	public void setSubscriptionPlan(String subscriptionPlan) {
		this.subscriptionPlan = subscriptionPlan;
	}

	public int getOtpResendCount() {
		return otpResendCount;
	}

	public void setOtpResendCount(int otpResendCount) {
		this.otpResendCount = otpResendCount;
	}

	public LocalDateTime getOtpResendBlockedUntil() {
		return otpResendBlockedUntil;
	}

	public void setOtpResendBlockedUntil(LocalDateTime otpResendBlockedUntil) {
		this.otpResendBlockedUntil = otpResendBlockedUntil;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", userId=" + userId + ", username=" + username + ", email=" + email
				+ ", phoneNumber=" + phoneNumber + ", passwordHash=" + passwordHash + ", gender=" + gender + ", dob="
				+ dob + ", enabled=" + enabled + ", currentOtp=" + currentOtp + ", otpExpiry=" + otpExpiry
				+ ", otpResendCount=" + otpResendCount + ", otpResendBlockedUntil=" + otpResendBlockedUntil + ", roles="
				+ roles + ", status=" + status + ", isFollowingTips=" + isFollowingTips + ", subscriptionPlan="
				+ subscriptionPlan + "]";
	}

}
